### ISSUE TITLE
Scraper only returns 1050 results

### ISSUE THREAD

**Issue by NickNicolaou2129** [toby-p/rightmove_webscraper.py#28]
Hi Toby, great scraper you got here, but it seems to be only returning 1050 results, I may just be using it wrong though..

I have loaded the script in PyCharm with the correct version of Python and have downloaded the dependencies.

I have entered this into the Python console:
from rightmove_webscraper import RightmoveData
url = "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E87490&propertyTypes=&includeSSTC=false&mustHave=&dontShow=&furnishTypes=&keywords="
rm = RightmoveData(url)
rm.results_count

![image](https://user-images.githubusercontent.com/31247621/86538184-4eb0f280-beec-11ea-9d63-a5aed5e4c6c3.png)

Even if I change the URL, the results still appear to be of 1050. Maybe my approach is wrong?

**Comment by toby-p** [comment]
Hi Nick, glad you are enjoying using the scraper! 

Unfortunately this is expected behaviour determined by the rightmove website, so is beyond our control. If you scroll to the bottom of the page of the url you used you'll see there are a total of 42 pages of results - each contains 25 listings, for a total of 1050. So even though the first results page states that there are 40,193 results, it is really only possible to see the first 1050.

The workaround to this limitation is to narrow the scope of the search, by searching for a smaller geographical area or by searching for listings published in a shorter period of time, and then to combine the results from multiple different searches.

I'll add something to the documentation to explain this limitation as this issue has been raised once or twice before. It also may be simple to modify the API so that you can pass multiple URLs to a single instance and scrape them all at once so I'll look into doing that too.

**Comment by alezenonos** [comment]
Is there a workaround on this, other than narrowing down the search area or time?

**Comment by toby-p** [comment]
As far as I know there isn't.
