### ISSUE TITLE
How can I print the results from get_results?

### ISSUE THREAD

**Issue by Brblol** [toby-p/rightmove_webscraper.py#29]
when I do print(rm.get_results()) I get something like this

```
     price  ...                search_date
0   230000  ... 2020-10-02 11:46:06.330777
1   715000  ... 2020-10-02 11:46:06.330777
```

And if I write it to file
```

f = open("output.html", "a")
f.write(str(rm.get_results))
f.close()
```

I still get the same thing. How can I see all of the columns?

**Comment by toby-p** [comment]
`get_results` is an instance of pandas.DataFrame (you don't need to call it because it's a property, not a method), so you can use any of the pandas options to save/export the data, e.g.:

to_csv - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html
to_html - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_html.html
to_json - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_json.html
... etc.

If you are using an interactive Python environment like Jupyter, then you can just execute the property as a statement and it will display inline (although often the data is truncated if a DataFrame is too big to display all data).
